### ISSUE TITLE
Flag '-v' does not exist error

### ISSUE THREAD

**Issue by lebogan** [mrrooijen/commander#16]
I am attempting to run the example from the readme and I get the above titled error. My invocation is:
crystal build src/my_cli.cr
./my_cli kill xx -v

Crystal 0.23.1
Commander 0.3.3

Thanks for any insights and please forgive my ignorance. Mark this as discuss.

**Comment by mrrooijen** [comment]
The `kill` command doesn't contain a `-v` flag. To add it to the `kill` command, use `flags.add` on the `kill`sub-command, like so:

```crystal
cmd.commands.add do |cmd|
  cmd.use = "kill <pid>"
  cmd.short = "Kills server by pid."
  cmd.long = cmd.short

  cmd.flags.add do |flag|
    flag.name = "verbose"
    flag.short = "-v"
    flag.long = "--verbose"
    flag.default = false
    flag.description = "Enable more verbose logging."
  end

  cmd.run do |options, arguments|
    arguments # => ["62719"]
  end
end
```

This can get quite redundant when you need to use the `-v` flag with multiple commands, so instead consider creating a reusable flag and apply it where necessary, like so:

```crystal
verbose_flag = Commander::Flag.new do |flag|
  flag.name = "verbose"
  flag.short = "-v"
  flag.long = "--verbose"
  flag.default = false
  flag.description = "Enable more verbose logging."
end

cmd.commands.add do |cmd|
  cmd.use = "kill <pid>"
  cmd.short = "Kills server by pid."
  cmd.long = cmd.short
  cmd.flags.add verbose_flag
  cmd.run do |options, arguments|
    arguments # => ["62719"]
  end
end
```

**Comment by lebogan** [comment]
@mrrooijen 
This is too cool. Works great! This shard goes a long way towards helping me migrate to Crystal from Ruby.
