### ISSUE TITLE
Hide or disable default "help" command

### ISSUE THREAD

**Issue by duraki** [mrrooijen/commander#17]
Hello and thank you for the library! 

Is it possible to not show `help` by default, or some way to disable ti?

https://github.com/mrrooijen/commander/blob/03742c065241165d5a292527c7039bfbb68349ee/src/commander/command.cr#L107

**Comment by mrrooijen** [comment]
Normally you'd configure your commands like so:

```crystal
Commander::Command.new do |cmd|
  # .. config here ..
end
```

In this case it'll build the help command into the help screen automatically. The `Commander::Command.new` function actually takes an optional argument (`help = false`). It defaults to `false` telling the internals that the help command isn't present in the help screen yet at this command level, so therefore create it. To prevent it from being automatically created, you want to pass in `true`.

For example:

```crystal
Commander::Command.new(true) do |cmd|
  # .. config here ..
end
```

Now the help command isn't rendered in the help screen itself any longer. However, the help command itself **is** still generated in the background and can be used explicitly.

The result with `help = true`:

    $ ./test
    # no output

    $ ./test help
    # no output, but also no error

    $ ./test --help
    Flag '--help' does not exist

But if you want display the help screen in certain situations, you can still invoke it explicitly from the run function:

```crystal
cmd.run do |options, arguments|
  if some_logic_applies
    puts cmd.help
  end
end
```

This would result in the rendering of the help screen as usual, but both the help command- and flag won't be shown.

Does that answer your question, or were you trying to accomplish something else?

**Comment by duraki** [comment]
That is exactly what I've asked for. I'm so sorry, I've missed the `Command` class initialization. Thank you for detailed response & solution.

**Comment by mrrooijen** [comment]
Glad to help.
