### ISSUE TITLE
Required/Mandatory Flags

### ISSUE THREAD

**Issue by jonahgeorge** [mrrooijen/commander#5]
What are you thoughts on supporting this feature request from the Ruby version of Commander?

https://github.com/tj/commander/issues/62
https://github.com/commander-rb/commander/issues/3

I would imagine that a required flag wouldn't also have a default value defined- this would mean that the flags would need their types defined via the api rather than inferred from the default value. Should a required flag not be provided, the program would exit early with a configurable message similar to "Option [name] is required.".

**Comment by mrrooijen** [comment]
Might be a useful feature to have. Perhaps with an API along the lines of:

``` crystal
  cmd.flags.add do |flag|
    flag.name = "port"
    flag.short = "-p"
    flag.long = "--port"
    flag.required = Int64 # instead of flag.default = 8080
    flag.description = "The port to bind to."
  end
```

**Comment by chyzwar** [comment]
I have the same issue. I would like have flags without default value and it is ok for it to be string.

**Comment by chyzwar** [comment]
Imo there are three things:

1. `flags.default` that would specify default value for flag if nothing is passed
2. `flags.required` that can specify if flag is mandatory, if nothing is passed for required = true, raise exception
3. `flags.type` that can specify casting to be performed, if none provided use String. 

All three flags should be optional, and if not provided, flag will have no default, optional and it will be casted to String?

If we can agree on some approach, I can take a look on making pull request,
