### ISSUE TITLE
Flagging Parent Command Breaks Subcommand

### ISSUE THREAD

**Issue by bramswenson** [mrrooijen/commander#7]
Given this slight modification to the example in the readme the subcommand is never called if flags defined in the parent are given: 

```
require "commander"

module TestSubCommands
  CLI = Commander::Command.new do |cmd|
    cmd.use = "my_program"
    cmd.long = "my program's (long) description."

    cmd.flags.add do |flag|
      flag.name = "env"
      flag.short = "-e"
      flag.long = "--env"
      flag.default = "development"
      flag.description = "The environment to run in."
    end 

    cmd.run do |options, arguments|
      puts "Running!"     
      puts options.string["env"]
      puts arguments
    end 

    cmd.commands.add do |cmd|
      cmd.use = "kill <pid>"
      cmd.short = "Kills server by pid."
      cmd.long = cmd.short
      cmd.run do |options, arguments|
        puts "Killing!
        puts options.string["env"]  
        puts arguments
      end 
    end 
  end
end

Commander.run(TestSubCommands::CLI, ARGV)
```

```
crystal build src/test_sub_commands.cr && ./test_sub_commands --env test kill foo bar 
Running!
test
["kill", "foo", "bar"]
```

For my purposes, and I think most, this would be more appropriate:

```
crystal build src/test_sub_commands.cr && ./test_sub_commands --env test kill foo bar 
Killing!
test
["foo", "bar"]
```

It seems like this should collect the flags defined in the parent command (which most would use as globals to be passed into child commands or available to them), search for a sub_command, and forward everything else should one be found.

Thoughts?

**Comment by bramswenson** [comment]
I suppose I conflated a bug and a feature request. The feature request being that parent flags are considered globals and passed to subcommands (or otherwise exposed to them). The bug is that if one defines a flag in the parent command along side a subcommand with different flags and passes in a parent flag when invoking, the subcommand is never called. Here is a test that demonstrates the core issue:

https://github.com/bramswenson/commander/commit/fffa045f13cce874fee33e8b5a7112454fce0118

**Comment by mrrooijen** [comment]
Good catch. That appears to be a bug.

Regarding flag reuse: It wasn't my intention to have the parent flags act as globals for all sub commands. Instead, the idea was to define flags separately (i.e. `verbose = Commander::Flag.new`) and then apply that `verbose` flag to each (sub)command (i.e. `cmd.flags.add verbose`) that needs the `--verbose` flag. This allows you to reuse the flag without block notation definitions all over the place, while also avoiding literally flags in all subcommands, when perhaps only a handful of subcommands actually make use of the flag.

**Comment by bramswenson** [comment]
@mrrooijen Sounds good to me. In #10 you will find a test proving out the failure. I haven't attempted to fix it yet.

**Comment by mrrooijen** [comment]
@bramswenson I actually miss-read the issue. The program is behaving as expected. The format is:

```
$ program [options] [arguments]
$ program [subcommand, ...] [options] [arguments]
```

This is intentional. I mistakenly miss-read your issue as:

```
$ program kill -e production 1
```

I thought you were pointing out that this invokes the top-level command, rather than the sub command, but it doesn't. Instead, it just says that `-e` doesn't exist on `kill`.

Is there a valid reason for wanting to be able to apply options before the sub command?

**Comment by bramswenson** [comment]
Yep, globals. Say configuration paths for example. If we have a command
that has many subcommands, but all depend on a common configuration file.
Maybe I want to give the `--config path` flag to every command. I totally
understand your logic about "not all flag should be global". However there
is, at least in my use, a persistent needs for global flags. I guess this
is a feature request after all :)

**Comment by bramswenson** [comment]
To your point, I can repeat all the flags in my subcommands (including the
globals), but it seems like unnecessary duplication from my perspective.

**Comment by mrrooijen** [comment]
Support was added for persistent flags in https://github.com/mrrooijen/commander/commit/50236aa610db9e45a6d5575bee80f52b8d6d0346.

Adding `flag.persistent = true` to a flag tells it to be recursively added to all child commands. Note that these aren't literally globals. You still invoke the flag after the sub command, but this does eliminate the duplication of defining and/or assigning the same flag to multiple commands. Any flag added to the root command with `flag.persistent = true` will be available in all commands.
